### ISSUE TITLE
Getting Permission denied on Sending Broadcast

### ISSUE THREAD

**Issue by samratashok87** [yandex-qatools/android-wifitool#5]
Hi , 

On using the command after installation of APP on Nexus , 

adb shell am broadcast  -n ru.yandex.qatools.wifitool/.Connect -e ssid ashok-udhaya -e securityString WPA -e pass usahome_01
Broadcasting: Intent { cmp=ru.yandex.qatools.wifitool/.Connect (has extras) }
Broadcast completed: result=0

Am getting the following error in logcat, 
 Permission Denial: broadcasting Intent { flg=0x10 cmp=ru.yandex.qatools.wifitool/.Connect (has extras) } from null (pid=15120, uid=2000) is not exported from uid 10094 due to receiver ru.yandex.qatools.wifitool/.Connect

Please let me know if anything I am missing. 

Thanks
Ashok

**Comment by kzaikin** [comment]
Is is fixed. You can build from latest sources or get the 1.0.1 release binary
https://github.com/yandex-qatools/android-wifitool/releases/tag/1.0.1

**Comment by samratashok87** [comment]
Thanks for the updated . I want to add 802.1x EAP Support, if ok please let me know where I can start looking regarding it in the source code.

**Comment by kzaikin** [comment]
Please check https://github.com/yandex-qatools/android-wifitool/blob/master/wifitool/src/main/java/ru/yandex/qatools/wifitool/utils/WifiConfigurationBuilder.java

Do you have a desired certificate installed on a device? I'm not sure a wifitool should be made able to install a certificate. There should be another tool for that.
